#Configuation for robot odometry EKF
#
frequency: 50

two_d_mode: true

publish_tf: true

transform_time_offset: 0.05

odom_frame: odom
base_link_frame: base_link
world_frame: map
map_frame: map

odom0: /odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true

imu0: /mavros/imu/data
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_differential: false

odom1: /odometry/gps
odom1_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom1_differential: false
